### PR TITLE
Fix renamed class.

### PR DESCRIPTION
**Pull request by spencergibb**

### CODE REVIEW

**Comment by bclozel** [comment]
Wow that was fast, the Boot build just finished.
Thanks a lot!

**Comment by spencergibb** [comment]
That's funny. I had no idea. I just rebuilt my project and it failed, so I made a PR.

**Comment by bclozel** [comment]
It seems the Boot changes broke integration tests support. I've ignore those in the application sample for now.

**Comment by spencergibb** [comment]
Yeah, I did notice that. Couldn't find `local.server.port`.

**Pull request merged**
